apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - image: brenobusnello/phpapp:6950f9c0b4e13db6a48e6ccd53418400dc9bcaaa
        name: php-app
        ports:
        - containerPort: 80
