apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - image: brenobusnello/phpapp:01f3bda4ba90f062b18de23e3488e04e5bd39b63
        name: php-app
        ports:
        - containerPort: 80
