apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - image: brenobusnello/phpapp:8e73f1acf2b472e67646c97d833652bdcc1a68f7
        name: php-app
        ports:
        - containerPort: 80
