apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - image: brenobusnello/phpapp:89b3ebf5a4e8549f7f3ccbeda11fbbbc367f84cd
        name: php-app
        ports:
        - containerPort: 80
