apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - image: brenobusnello/phpapp:f626d97f7493e759c579d04fed77b432b7d7fa44
        name: php-app
        ports:
        - containerPort: 80
